export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_SUBPAGE = 'UPDATE_SUBPAGE';
export const UPDATE_SUB_PAGE_ROUTE = 'UPDATE_SUB_PAGE_ROUTE';
export const FETCH_USER_SONGS = "FETCH_USER_SONGS"; 
export const FETCH_USER_PLAYLISTS = "FETCH_USER_PLAYLISTS"; 
export const FETCH_PLAYLIST_SONGS = "FETCH_PLAYLIST_SONGS"; 
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SETUP_MUSICKIT = "SETUP_MUSICKIT";
export const CREATE_ALERT = "CREATE_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";
export const PLAY_SONG = "PLAY_SONG";
export const SET_SONGS_IN_VIEW = "SET_SONGS_IN_VIEW";
export const SONG_LOADING_CHECKER = "SONG_LOADING_CHECKER";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";

// recentTrendingActions.js
export const GET_RECENTLY_SEARCHED_ITEMS = "GET_RECENTLY_SEARCHED_ITEMS";
export const ADD_RECENTLY_SEARCHED_ITEM = "ADD_RECENTLY_SEARCHED_ITEM";
export const CLEAR_RECENTLY_SEARCHED_ITEMS = "CLEAR_RECENTLY_SEARCHED_ITEMS";
export const GET_TRENDING_ITEMS = "GET_TRENDING_ITEMS";
