export const UPDATE_PAGE = 'UPDATE_PAGE';
export const FETCH_USER_SONGS = "FETCH_USER_SONGS"; 
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const SETUP_MUSICKIT = "SETUP_MUSICKIT";
export const CREATE_ALERT = "CREATE_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";